vich_uploader:
    db_driver: orm

    mappings:
       billets:
           uri_prefix: /images/billets
           upload_destination: '%kernel.project_dir%/public/images/billets'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
